//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Database1Model", "FK_Listas_ToTable", "Sedes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CentroAlumnos.Sedes), "Listas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CentroAlumnos.Listas), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "FK_Votos_ToTable", "Listas", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CentroAlumnos.Listas), "Votos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CentroAlumnos.Votos), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "FK_Usuarios_ToTable", "Sedes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CentroAlumnos.Sedes), "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CentroAlumnos.Usuarios), true)]
[assembly: EdmRelationshipAttribute("Database1Model", "FK_Votos_ToTable_1", "Sedes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CentroAlumnos.Sedes), "Votos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CentroAlumnos.Votos), true)]

#endregion

namespace CentroAlumnos
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Database1Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Database1Entities1 object using the connection string found in the 'Database1Entities1' section of the application configuration file.
        /// </summary>
        public Database1Entities1() : base("name=Database1Entities1", "Database1Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities1 object.
        /// </summary>
        public Database1Entities1(string connectionString) : base(connectionString, "Database1Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Database1Entities1 object.
        /// </summary>
        public Database1Entities1(EntityConnection connection) : base(connection, "Database1Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Listas> Listas
        {
            get
            {
                if ((_Listas == null))
                {
                    _Listas = base.CreateObjectSet<Listas>("Listas");
                }
                return _Listas;
            }
        }
        private ObjectSet<Listas> _Listas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sedes> Sedes
        {
            get
            {
                if ((_Sedes == null))
                {
                    _Sedes = base.CreateObjectSet<Sedes>("Sedes");
                }
                return _Sedes;
            }
        }
        private ObjectSet<Sedes> _Sedes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Votos> Votos
        {
            get
            {
                if ((_Votos == null))
                {
                    _Votos = base.CreateObjectSet<Votos>("Votos");
                }
                return _Votos;
            }
        }
        private ObjectSet<Votos> _Votos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Listas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToListas(Listas listas)
        {
            base.AddObject("Listas", listas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sedes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSedes(Sedes sedes)
        {
            base.AddObject("Sedes", sedes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Votos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVotos(Votos votos)
        {
            base.AddObject("Votos", votos);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Listas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Listas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Listas object.
        /// </summary>
        /// <param name="listaId">Initial value of the ListaId property.</param>
        public static Listas CreateListas(global::System.Int32 listaId)
        {
            Listas listas = new Listas();
            listas.ListaId = listaId;
            return listas;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListaId
        {
            get
            {
                return _ListaId;
            }
            set
            {
                if (_ListaId != value)
                {
                    OnListaIdChanging(value);
                    ReportPropertyChanging("ListaId");
                    _ListaId = StructuralObject.SetValidValue(value, "ListaId");
                    ReportPropertyChanged("ListaId");
                    OnListaIdChanged();
                }
            }
        }
        private global::System.Int32 _ListaId;
        partial void OnListaIdChanging(global::System.Int32 value);
        partial void OnListaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Presidente
        {
            get
            {
                return _Presidente;
            }
            set
            {
                OnPresidenteChanging(value);
                ReportPropertyChanging("Presidente");
                _Presidente = StructuralObject.SetValidValue(value, true, "Presidente");
                ReportPropertyChanged("Presidente");
                OnPresidenteChanged();
            }
        }
        private global::System.String _Presidente;
        partial void OnPresidenteChanging(global::System.String value);
        partial void OnPresidenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VicePresidente
        {
            get
            {
                return _VicePresidente;
            }
            set
            {
                OnVicePresidenteChanging(value);
                ReportPropertyChanging("VicePresidente");
                _VicePresidente = StructuralObject.SetValidValue(value, true, "VicePresidente");
                ReportPropertyChanged("VicePresidente");
                OnVicePresidenteChanged();
            }
        }
        private global::System.String _VicePresidente;
        partial void OnVicePresidenteChanging(global::System.String value);
        partial void OnVicePresidenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Secretario
        {
            get
            {
                return _Secretario;
            }
            set
            {
                OnSecretarioChanging(value);
                ReportPropertyChanging("Secretario");
                _Secretario = StructuralObject.SetValidValue(value, true, "Secretario");
                ReportPropertyChanged("Secretario");
                OnSecretarioChanged();
            }
        }
        private global::System.String _Secretario;
        partial void OnSecretarioChanging(global::System.String value);
        partial void OnSecretarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SedeId
        {
            get
            {
                return _SedeId;
            }
            set
            {
                OnSedeIdChanging(value);
                ReportPropertyChanging("SedeId");
                _SedeId = StructuralObject.SetValidValue(value, "SedeId");
                ReportPropertyChanged("SedeId");
                OnSedeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SedeId;
        partial void OnSedeIdChanging(Nullable<global::System.Int32> value);
        partial void OnSedeIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Listas_ToTable", "Sedes")]
        public Sedes Sedes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Listas_ToTable", "Sedes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Listas_ToTable", "Sedes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sedes> SedesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Listas_ToTable", "Sedes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sedes>("Database1Model.FK_Listas_ToTable", "Sedes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Votos_ToTable", "Votos")]
        public EntityCollection<Votos> Votos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Votos>("Database1Model.FK_Votos_ToTable", "Votos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Votos>("Database1Model.FK_Votos_ToTable", "Votos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Sedes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sedes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sedes object.
        /// </summary>
        /// <param name="sedeId">Initial value of the SedeId property.</param>
        public static Sedes CreateSedes(global::System.Int32 sedeId)
        {
            Sedes sedes = new Sedes();
            sedes.SedeId = sedeId;
            return sedes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SedeId
        {
            get
            {
                return _SedeId;
            }
            set
            {
                if (_SedeId != value)
                {
                    OnSedeIdChanging(value);
                    ReportPropertyChanging("SedeId");
                    _SedeId = StructuralObject.SetValidValue(value, "SedeId");
                    ReportPropertyChanged("SedeId");
                    OnSedeIdChanged();
                }
            }
        }
        private global::System.Int32 _SedeId;
        partial void OnSedeIdChanging(global::System.Int32 value);
        partial void OnSedeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Zona
        {
            get
            {
                return _Zona;
            }
            set
            {
                OnZonaChanging(value);
                ReportPropertyChanging("Zona");
                _Zona = StructuralObject.SetValidValue(value, "Zona");
                ReportPropertyChanged("Zona");
                OnZonaChanged();
            }
        }
        private Nullable<global::System.Int32> _Zona;
        partial void OnZonaChanging(Nullable<global::System.Int32> value);
        partial void OnZonaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Listas_ToTable", "Listas")]
        public EntityCollection<Listas> Listas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Listas>("Database1Model.FK_Listas_ToTable", "Listas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Listas>("Database1Model.FK_Listas_ToTable", "Listas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Usuarios_ToTable", "Usuarios")]
        public EntityCollection<Usuarios> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuarios>("Database1Model.FK_Usuarios_ToTable", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuarios>("Database1Model.FK_Usuarios_ToTable", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Votos_ToTable_1", "Votos")]
        public EntityCollection<Votos> Votos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Votos>("Database1Model.FK_Votos_ToTable_1", "Votos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Votos>("Database1Model.FK_Votos_ToTable_1", "Votos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="usuarioId">Initial value of the UsuarioId property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 usuarioId)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.UsuarioId = usuarioId;
            return usuarios;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioId
        {
            get
            {
                return _UsuarioId;
            }
            set
            {
                if (_UsuarioId != value)
                {
                    OnUsuarioIdChanging(value);
                    ReportPropertyChanging("UsuarioId");
                    _UsuarioId = StructuralObject.SetValidValue(value, "UsuarioId");
                    ReportPropertyChanged("UsuarioId");
                    OnUsuarioIdChanged();
                }
            }
        }
        private global::System.Int32 _UsuarioId;
        partial void OnUsuarioIdChanging(global::System.Int32 value);
        partial void OnUsuarioIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rol
        {
            get
            {
                return _Rol;
            }
            set
            {
                OnRolChanging(value);
                ReportPropertyChanging("Rol");
                _Rol = StructuralObject.SetValidValue(value, true, "Rol");
                ReportPropertyChanged("Rol");
                OnRolChanged();
            }
        }
        private global::System.String _Rol;
        partial void OnRolChanging(global::System.String value);
        partial void OnRolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VotoRealizado
        {
            get
            {
                return _VotoRealizado;
            }
            set
            {
                OnVotoRealizadoChanging(value);
                ReportPropertyChanging("VotoRealizado");
                _VotoRealizado = StructuralObject.SetValidValue(value, "VotoRealizado");
                ReportPropertyChanged("VotoRealizado");
                OnVotoRealizadoChanged();
            }
        }
        private Nullable<global::System.Int32> _VotoRealizado;
        partial void OnVotoRealizadoChanging(Nullable<global::System.Int32> value);
        partial void OnVotoRealizadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SedeId
        {
            get
            {
                return _SedeId;
            }
            set
            {
                OnSedeIdChanging(value);
                ReportPropertyChanging("SedeId");
                _SedeId = StructuralObject.SetValidValue(value, "SedeId");
                ReportPropertyChanged("SedeId");
                OnSedeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SedeId;
        partial void OnSedeIdChanging(Nullable<global::System.Int32> value);
        partial void OnSedeIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Usuarios_ToTable", "Sedes")]
        public Sedes Sedes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Usuarios_ToTable", "Sedes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Usuarios_ToTable", "Sedes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sedes> SedesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Usuarios_ToTable", "Sedes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sedes>("Database1Model.FK_Usuarios_ToTable", "Sedes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Database1Model", Name="Votos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Votos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Votos object.
        /// </summary>
        /// <param name="votoId">Initial value of the VotoId property.</param>
        public static Votos CreateVotos(global::System.Int32 votoId)
        {
            Votos votos = new Votos();
            votos.VotoId = votoId;
            return votos;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VotoId
        {
            get
            {
                return _VotoId;
            }
            set
            {
                if (_VotoId != value)
                {
                    OnVotoIdChanging(value);
                    ReportPropertyChanging("VotoId");
                    _VotoId = StructuralObject.SetValidValue(value, "VotoId");
                    ReportPropertyChanged("VotoId");
                    OnVotoIdChanged();
                }
            }
        }
        private global::System.Int32 _VotoId;
        partial void OnVotoIdChanging(global::System.Int32 value);
        partial void OnVotoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SedeId
        {
            get
            {
                return _SedeId;
            }
            set
            {
                OnSedeIdChanging(value);
                ReportPropertyChanging("SedeId");
                _SedeId = StructuralObject.SetValidValue(value, "SedeId");
                ReportPropertyChanged("SedeId");
                OnSedeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _SedeId;
        partial void OnSedeIdChanging(Nullable<global::System.Int32> value);
        partial void OnSedeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ListaId
        {
            get
            {
                return _ListaId;
            }
            set
            {
                OnListaIdChanging(value);
                ReportPropertyChanging("ListaId");
                _ListaId = StructuralObject.SetValidValue(value, "ListaId");
                ReportPropertyChanged("ListaId");
                OnListaIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ListaId;
        partial void OnListaIdChanging(Nullable<global::System.Int32> value);
        partial void OnListaIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Votos_ToTable", "Listas")]
        public Listas Listas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Listas>("Database1Model.FK_Votos_ToTable", "Listas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Listas>("Database1Model.FK_Votos_ToTable", "Listas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Listas> ListasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Listas>("Database1Model.FK_Votos_ToTable", "Listas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Listas>("Database1Model.FK_Votos_ToTable", "Listas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Database1Model", "FK_Votos_ToTable_1", "Sedes")]
        public Sedes Sedes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Votos_ToTable_1", "Sedes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Votos_ToTable_1", "Sedes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sedes> SedesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sedes>("Database1Model.FK_Votos_ToTable_1", "Sedes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sedes>("Database1Model.FK_Votos_ToTable_1", "Sedes", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
